apiVersion: v1
kind: Service
metadata:
  name: graphite-service
  labels:
    app: graphite
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
    - port: 2003
      targetPort: 2003
      protocol: TCP
      name: carbon
    - port: 8125
      targetPort: 8125
      protocol: UDP
      name: statsd
  selector:
    app: graphite
