apiVersion: v1
kind: Service
metadata:
  name: statsd-service
  labels:
    app: statsd
spec:
  type: ClusterIP # You can change to NodePort or LoadBalancer if needed
  ports:
    - port: 8125
      targetPort: 8125
      protocol: UDP
      name: statsd-udp
    - port: 8126
      targetPort: 8126
      protocol: TCP
      name: statsd-tcp
  selector:
    app: statsd
