apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd
  labels:
    app: statsd
spec:
  replicas: 1 # Number of desired pods
  selector:
    matchLabels:
      app: statsd
  template:
    metadata:
      labels:
        app: statsd
    spec:
      containers:
        - name: statsd
          image: statsd/statsd:latest # Replace with the desired StatsD image
          ports:
            - containerPort: 8125
              protocol: UDP
            - containerPort: 8126
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
